### ISSUE TITLE
Can I launch it in IDLE (Python 3.5 32-bit)

### ISSUE THREAD

**Issue by ghost** [Jackeriss/Companions#1]
Does it support python 3?

**Comment by Jackeriss** [comment]
It is written in Python 2.7, and doesn't support python 3.

**Comment by ghost** [comment]
Thanks, I want rewrite it in python3. :)

2016-02-12 15:44 GMT+08:00 Jack Criss notifications@github.com:

**Comment by Jackeriss** [comment]
Waiting for your good news! If you meet any problem, ask me. I will try my best to support you!
