### ISSUE TITLE
为什么不链接上微软“Cortana”？

### ISSUE THREAD

**Issue by ghost** [Jackeriss/Companions#2]
目前这个PA在意识上还有很多缺点，比如：

> 我：御坂
> 御坂10032号：不知道“御坂”是什么意思，你可以百度一下，do，御坂一本正经地说道

如果能够链接上微软[Cortana的的API](https://dev.windows.com/en-us/cortana)，或许实现一些更高级的对话。

**Comment by Jackeriss** [comment]
因为本来我是倾向于功能的，就是想做得实用一点，然后对话这块我想自己实现一个简单一点的，毕竟要是直接调用API好像就没自己什么事了。。。可我显然是没有这方面的经验，关键还必须有数据支持。。。于是就想办法支持了百度知道的推荐回答和互动百科等。说白了就是不想只做一个空壳，就算做的不好也是完全自主研发233，如果真想做成产品当然还是调API吧，我主要是自娱自乐。

**Comment by ghost** [comment]
我也来娱乐一下2333
